### ISSUE TITLE
Intensity normalization as preprocessing step

### ISSUE THREAD

**Issue by RocaVincent** [bigting84/style_transfer_harmonization#1]
Hi, I tried your model and it seemed to me that it performed a maximum normalization (rescaling between -1 and 1) before giving the image to the harmonization model. The harmonized image is thus in a similar intensity range ([-1,1]).

Can you confirm that ? Thanks in advance.

**Comment by vakharia-aarya** [comment]
Yes, that is correct. The model scales the intensities to -1 and 1.  
We have added new post-processing scripts to rescale the images back to their original intensities.
