### ISSUE TITLE
Error in inner loop when harmonizing images

### ISSUE THREAD

**Issue by RocaVincent** [bigting84/style_transfer_harmonization#3]
In *harmonize_images.sh*, an inner loop iterates over source dirs for each subject (line 44). I think the idea is to iterate over *axial*, *coronal* and *sagittal*. However, there is also a *npy* created line 40. So the loop iterates on this dir and you then have the following error:
```
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 61, in main
    assert len(subdirs(args.src_dir)) == args.num_domains
AssertionError
```

**Comment by vakharia-aarya** [comment]
Issues has been resolved in the recent commit
